import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { options } from "../api/auth/[...nextauth]/options";
import { redirect } from "next/navigation";
import LogoutBtn from "../components/logout-btn";
import Link from "next/link";
import { GoHome } from "react-icons/go";
import { RiUser3Line } from "react-icons/ri";
import { MdLogout } from "react-icons/md";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await getServerSession(options);

	if (session?.user.is_admin) {
		redirect("/admin");
	}

	return (
		<div className="drawer">
			<input
				id="my-drawer-3"
				type="checkbox"
				className="drawer-toggle"
			/>
			<div className="drawer-content flex flex-col">
				{/* Navbar */}
				<div className="w-full navbar bg-base-200">
					<div className="flex-none lg:hidden">
						<label
							htmlFor="my-drawer-3"
							aria-label="open sidebar"
							className="btn btn-square btn-ghost"
						>
							<svg
								xmlns="http://www.w3.org/2000/svg"
								fill="none"
								viewBox="0 0 24 24"
								className="inline-block w-6 h-6 stroke-current"
							>
								<path
									strokeLinecap="round"
									strokeLinejoin="round"
									strokeWidth="2"
									d="M4 6h16M4 12h16M4 18h16"
								></path>
							</svg>
						</label>
					</div>
					<div className="flex-1 px-2 mx-2">
						<Link
							href="/user"
							className="font-bold"
						>
							FUPRE
						</Link>
					</div>
					<div className="flex-none hidden lg:block">
						<ul className="menu menu-horizontal">
							{/* Navbar menu content here */}
							<li>
								<Link href="/user/profile">Profile</Link>
							</li>
						</ul>
						<LogoutBtn className="btn btn-error btn-sm">
							Log out
						</LogoutBtn>
					</div>
				</div>
				{/* Page content here */}
				<main className="w-full flex-1 p-5">{children}</main>
			</div>
			<div className="drawer-side">
				<label
					htmlFor="my-drawer-3"
					aria-label="close sidebar"
					className="drawer-overlay"
				></label>
				<div className="menu p-4 w-80 min-h-full bg-base-200 flex flex-col justify-between">
					<div>
						<div className="pl-4">
							<h1 className="font-bold">FUPRE geo-location</h1>
							<p className="text-xs">Attendance system</p>
						</div>
						<ul className="mt-5">
							{/* Sidebar content here */}
							<li>
								<Link href="/user">
									<GoHome className="w-5 h-5" />
									Home
								</Link>
							</li>
							<li>
								<Link href="/user/profile">
									<RiUser3Line className="w-5 h-5" />
									Profile
								</Link>
							</li>
						</ul>
					</div>
					<LogoutBtn className="btn btn-error btn-sm">
						Log out
						<MdLogout className="w-5 h-5" />
					</LogoutBtn>
				</div>
			</div>
		</div>
	);
}
