import type { Metadata } from "next";
import Link from "next/link";
import { HiOutlineBars3CenterLeft } from "react-icons/hi2";
import LogoutBtn from "../components/logout-btn";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<div className="drawer lg:drawer-open">
			<input
				id="my-drawer-2"
				type="checkbox"
				className="drawer-toggle"
			/>
			<div className="drawer-content flex flex-col items-center justify-center">
				{/* Page content here */}
				<main className="flex-1 w-full p-5">
					<label
						htmlFor="my-drawer-2"
						className="btn btn-primary drawer-button lg:hidden"
					>
						<HiOutlineBars3CenterLeft />
					</label>
					{children}
				</main>
			</div>
			<div className="drawer-side">
				<label
					htmlFor="my-drawer-2"
					aria-label="close sidebar"
					className="drawer-overlay"
				></label>
				<div className="menu p-4 w-80 min-h-full bg-base-200 text-base-content">
					<ul className="">
						{/* Sidebar content here */}

						<li>
							<Link href={"/admin"}>Dashboard</Link>
						</li>
						<li>
							<Link href={"/admin/coordinate"}>Coordinates</Link>
						</li>
						<li>
							<Link href={"/admin/profiles"}>Profiles</Link>
						</li>
					</ul>
					<LogoutBtn className="btn btn-error">Logout</LogoutBtn>
				</div>
			</div>
		</div>
	);
}
